---

- name: get latest release
  delegate_to: localhost
  become: false
  run_once: true
  when:
    - kimai_version == "latest"
  block:
    - name: get latest release
      bodsch.scm.github_latest:
        project: kimai
        repository: kimai
        user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
        password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
      register: _latest_release

    - name: set kimai version
      ansible.builtin.set_fact:
        kimai_version: "{{ _latest_release.latest_release }}"

- name: define download information
  ansible.builtin.set_fact:
    kimai_release: "{{ kimai_defaults_release | combine(kimai_release, recursive=True) }}"

- name: define delegate instance for download handling
  ansible.builtin.set_fact:
    kimai_delegate_to: "{{ ansible_host }}"
    kimai_local_tmp_directory: "{{
        lookup('env', 'CUSTOM_LOCAL_TMP_DIRECTORY') |
        default('/var/cache/ansible/kimai', true) }}/{{ kimai_version }}"
  when:
    - kimai_direct_download

- name: create download directory
  become: false
  delegate_to: "{{ kimai_delegate_to }}"
  run_once: "{{ 'false' if kimai_direct_download else 'true' }}"
  ansible.builtin.file:
    path: "{{ kimai_local_tmp_directory }}"
    state: directory
    mode: "0750"

- name: detect the downloaded kimai archive
  become: false
  delegate_to: "{{ kimai_delegate_to }}"
  run_once: "{{ 'false' if kimai_direct_download else 'true' }}"
  ansible.builtin.stat:
    path: "{{ kimai_local_tmp_directory }}/{{ kimai_release.file }}"
  register: stat_kimai_archive


- name: download
  when:
    - stat_kimai_archive.stat is defined
    - not stat_kimai_archive.stat.exists | default('false')
  block:
    # - name: checksum
    #   become: false
    #   delegate_to: localhost
    #   run_once: true
    #   block:
    #     - name: get checksum list
    #       bodsch.scm.github_checksum:
    #         project: kimai
    #         repository: kimai
    #         checksum_file: "{{ kimai_release.checksum }}"
    #         user: "{{ lookup('env', 'GH_USER') | default(omit) }}"
    #         password: "{{ lookup('env', 'GH_TOKEN') | default(omit) }}"
    #         architecture: "{{ ansible_architecture }}"
    #         system: "{{ ansible_facts.system }}"
    #         version: "{{ kimai_version }}"
    #       register: _latest_checksum
    #
    #     - name: define checksum for {{ system_architecture }} architecture
    #       ansible.builtin.set_fact:
    #         __kimai_checksum: "sha256:{{ _latest_checksum.checksum }}"
    #       when:
    #         - _latest_checksum.rc == 0
    #         - _latest_checksum.checksum is defined
    #         - _latest_checksum.checksum | string | length > 0

    - name: download kimai binary archive
      become: false
      delegate_to: "{{ kimai_delegate_to }}"
      run_once: "{{ 'false' if kimai_direct_download else 'true' }}"
      ansible.builtin.get_url:
        url: "{{ kimai_release.download_url }}/archive/refs/tags/{{ kimai_release.file }}"
        dest: "{{ kimai_local_tmp_directory }}/{{ kimai_release.file }}"
        checksum: "{{ __kimai_checksum | default(omit) }}"
        mode: "0660"
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

  rescue:
    - name: delete download directory
      become: false
      delegate_to: "{{ kimai_delegate_to }}"
      run_once: "{{ 'false' if kimai_direct_download else 'true' }}"
      ansible.builtin.file:
        path: "{{ kimai_local_tmp_directory }}"
        state: absent

    - name: exit with fail
      ansible.builtin.fail:
        msg: A serious error occurred when downloading the archive.

...
