---

- name: prepare
  ansible.builtin.include_tasks: prepare.yml
  tags:
    - kimai_prepare
    - kimai_configure

- name: download
  ansible.builtin.include_tasks: download.yml
  tags:
    - kimai_download

- name: install
  ansible.builtin.include_tasks: install.yml
  tags:
    - kimai_install

- name: configure
  ansible.builtin.include_tasks: configure.yml
  tags:
    - kimai_configure

...
