---

mariadb_use_external_repo: true

mariadb_debian_repo: https://dlm.mariadb.com/repo
mariadb_version: 12.rolling

mariadb_system_users:
  - username: root
    password: ""
    home: /root
    update: true
    ignore: true

mariadb_databases:
  - name: kimai

mariadb_users:
  - name: kimai
    host: "%"
    password: kimai
    encrypted: false
    priv: "kimai.*:ALL"

mariadb_config_mysqld:
  bind-address: 0.0.0.0
  # socket: "{{ mariadb_socket }}"
  skip-external-locking:
  skip-name-resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20
