---

nginx_gzip:
  enabled: true

nginx_logformat:
  json_combined:
    format: |
      '{'
        '"time_local": "$time_local",'
        '"remote_addr": "$remote_addr",'
        '"remote_user": "$remote_user",'
        '"request": "$request",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"request_time": "$request_time",'
        '"http_referrer": "$http_referer",'
        '"http_user_agent": "$http_user_agent"'
      '}';

nginx_vhosts:
  - name: kimai
    filename: 00-kimai.conf
    state: present
    enabled: true

    domains:
      - kimai.molecule.lan

    listen:
      - 80

    root_directory: "{{ kimai_install_base_directory }}/kimai/public"
    root_directory_create: false

    index:
      - index.php

    logfiles:
      access:
        file: /var/log/nginx/kimai.molecule.lan/access.log
        loglevel: json_combined
      error:
        file: /var/log/nginx/kimai.molecule.lan/error.log

    locations:

      "~ /\\.ht":
        options: |
          deny all;

      "/":
        options: |
          try_files $uri /index.php$is_args$args;


      "~ ^/index\\.php(/|$)":
        options: |
          fastcgi_index             index.php;
          fastcgi_split_path_info   ^(.+\.php)(/.*)$;
          fastcgi_read_timeout      600;
          fastcgi_pass              unix:/run/php/worker-01.sock;

          include fastcgi_params;
          fastcgi_param             SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
          fastcgi_param             DOCUMENT_ROOT $realpath_root;

          internal;

      "~ \\.php$":
        options: |
          return 404;
